/*
	Controllo versione DB MRT 750
*/
DECLARE @MRTVERSION AS NVARCHAR(10)
SELECT @MRTVERSION = T05VALORE FROM T05COMFLAGS WHERE T05POSTAZIONE='COMF' AND T05TIPO='DBVER'
IF (@MRTVERSION <> '7.50')
BEGIN
	PRINT 'Versione database errata'
	RETURN
END
GO

-- Versione maggiore OK
PRINT 'Versione database 7.50'

-- Controlla versione 100 (MRTCore 7.5.6)
IF OBJECT_ID(N'dbo.T143MESSAGETEMPLATE', N'U') IS NOT NULL
BEGIN
	PRINT 'Script level 100 ok'
END
ELSE
BEGIN
	-- Script di update DB con campi per gestione avanzata visitatori MrtCore 7.5.6

	CREATE TABLE [dbo].[T143MESSAGETEMPLATE] (
		[T143ID] [int] NOT NULL IDENTITY,
		[T143TYPE] [int] NOT NULL,
		[T143DESCRIPTION] [nvarchar](60),
		[T143UTENTEMODIFICA] [nvarchar](255) NOT NULL,
		[T143DATAORAMODIFICA] [datetime] NOT NULL,
		CONSTRAINT [PK_dbo.T143MESSAGETEMPLATE] PRIMARY KEY ([T143ID])
	)
	CREATE TABLE [dbo].[T144MESSAGETEMPLATEDETAIL] (
		[T144ID] [int] NOT NULL IDENTITY,
		[T144PARENTID] [int] NOT NULL,
		[T144LANGUAGECODE] [nvarchar](5),
		[T144SUBJECT] [nvarchar](255) NOT NULL,
		[T144BODY] [nvarchar](max) NOT NULL,
		[T144UTENTEMODIFICA] [nvarchar](255) NOT NULL,
		[T144DATAORAMODIFICA] [datetime] NOT NULL,
		CONSTRAINT [PK_dbo.T144MESSAGETEMPLATEDETAIL] PRIMARY KEY ([T144ID], [T144PARENTID])
	)
	CREATE INDEX [IX_T144PARENTID] ON [dbo].[T144MESSAGETEMPLATEDETAIL]([T144PARENTID])
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118ISRECEPTIONSITE] [bit] NOT NULL DEFAULT 0
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118VISRECEPTIONENTRGROUPCODE] [nvarchar](8)
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118VISPARKINGENTRGROUPCODE] [nvarchar](8)
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118VISTIMESLOTCODE] [nvarchar](3)
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118VISMINBEFOREALLOWED] [int] NOT NULL DEFAULT 0
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118VISMINAFTERALLOWED] [int] NOT NULL DEFAULT 0
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118VISEMAILTEMPLATEID] [int]
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118VISEMAILSENDER] [nvarchar](255)
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118VISAUTOEXTREG] [bit] NOT NULL DEFAULT 0
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118VISTERMINALCODE] [nvarchar](8)
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118VISENTRANCECODE] [nvarchar](8)
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118VISMODELCODE] [nvarchar](8)
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118SUPPORTEDLANGUAGES] [nvarchar](max)
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD [T118DEFAULTLANGUAGECODE] [nvarchar](5)
	ALTER TABLE [dbo].[T31COMVISITATORI] ADD [T31LANGUAGECODE] [nvarchar](5)
	ALTER TABLE [dbo].[T123ACCFASTPRENVISITATORI] ADD [T123LANGUAGECODE] [nvarchar](5)
	ALTER TABLE [dbo].[T123ACCFASTPRENVISITATORI] ADD [T123LOGICALSITECODE] [nvarchar](4)
	ALTER TABLE [dbo].[T123ACCFASTPRENVISITATORI] ADD [T123FLAGPRIVACY] [bit] NOT NULL DEFAULT 0
	ALTER TABLE [dbo].[T142COMDETTDOCUMENTALE] ADD [T142LANGUAGECODE] [nvarchar](5)
	ALTER TABLE [dbo].[T142COMDETTDOCUMENTALE] ADD [T142DESCRIPTION] [nvarchar](60)
	CREATE INDEX [IX_T118VISRECEPTIONENTRGROUPCODE] ON [dbo].[T118ACCSEDILOGICHE]([T118VISRECEPTIONENTRGROUPCODE])
	CREATE INDEX [IX_T118VISPARKINGENTRGROUPCODE] ON [dbo].[T118ACCSEDILOGICHE]([T118VISPARKINGENTRGROUPCODE])
	CREATE INDEX [IX_T118VISTIMESLOTCODE] ON [dbo].[T118ACCSEDILOGICHE]([T118VISTIMESLOTCODE])
	CREATE INDEX [IX_T118VISEMAILTEMPLATEID] ON [dbo].[T118ACCSEDILOGICHE]([T118VISEMAILTEMPLATEID])
	CREATE INDEX [IX_T118VISTERMINALCODE] ON [dbo].[T118ACCSEDILOGICHE]([T118VISTERMINALCODE])
	CREATE INDEX [IX_T118VISENTRANCECODE] ON [dbo].[T118ACCSEDILOGICHE]([T118VISENTRANCECODE])
	CREATE INDEX [IX_T118VISMODELCODE] ON [dbo].[T118ACCSEDILOGICHE]([T118VISMODELCODE])
	CREATE INDEX [IX_T123LOGICALSITECODE] ON [dbo].[T123ACCFASTPRENVISITATORI]([T123LOGICALSITECODE])
	ALTER TABLE [dbo].[T123ACCFASTPRENVISITATORI] ADD CONSTRAINT [FK_dbo.T123ACCFASTPRENVISITATORI_dbo.T118ACCSEDILOGICHE_T123LOGICALSITECODE] FOREIGN KEY ([T123LOGICALSITECODE]) REFERENCES [dbo].[T118ACCSEDILOGICHE] ([T118CODICE])
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD CONSTRAINT [FK_dbo.T118ACCSEDILOGICHE_dbo.T23ACCVARCHI_T118VISENTRANCECODE] FOREIGN KEY ([T118VISENTRANCECODE]) REFERENCES [dbo].[T23ACCVARCHI] ([T23CODICE])
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD CONSTRAINT [FK_dbo.T118ACCSEDILOGICHE_dbo.T143MESSAGETEMPLATE_T118VISEMAILTEMPLATEID] FOREIGN KEY ([T118VISEMAILTEMPLATEID]) REFERENCES [dbo].[T143MESSAGETEMPLATE] ([T143ID])
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD CONSTRAINT [FK_dbo.T118ACCSEDILOGICHE_dbo.T45ACCMVABILITAZIONI_T118VISMODELCODE] FOREIGN KEY ([T118VISMODELCODE]) REFERENCES [dbo].[T45ACCMVABILITAZIONI] ([T45CODICE])
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD CONSTRAINT [FK_dbo.T118ACCSEDILOGICHE_dbo.T27ACCTGRUPPIVARCHI_T118VISPARKINGENTRGROUPCODE] FOREIGN KEY ([T118VISPARKINGENTRGROUPCODE]) REFERENCES [dbo].[T27ACCTGRUPPIVARCHI] ([T27CODICE])
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD CONSTRAINT [FK_dbo.T118ACCSEDILOGICHE_dbo.T27ACCTGRUPPIVARCHI_T118VISRECEPTIONENTRGROUPCODE] FOREIGN KEY ([T118VISRECEPTIONENTRGROUPCODE]) REFERENCES [dbo].[T27ACCTGRUPPIVARCHI] ([T27CODICE])
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD CONSTRAINT [FK_dbo.T118ACCSEDILOGICHE_dbo.T22ACCTERMINALI_T118VISTERMINALCODE] FOREIGN KEY ([T118VISTERMINALCODE]) REFERENCES [dbo].[T22ACCTERMINALI] ([T22CODICE])
	ALTER TABLE [dbo].[T118ACCSEDILOGICHE] ADD CONSTRAINT [FK_dbo.T118ACCSEDILOGICHE_dbo.T33ACCFASCE_T118VISTIMESLOTCODE] FOREIGN KEY ([T118VISTIMESLOTCODE]) REFERENCES [dbo].[T33ACCFASCE] ([T33CODICE])
	ALTER TABLE [dbo].[T144MESSAGETEMPLATEDETAIL] ADD CONSTRAINT [FK_dbo.T144MESSAGETEMPLATEDETAIL_dbo.T143MESSAGETEMPLATE_T144PARENTID] FOREIGN KEY ([T144PARENTID]) REFERENCES [dbo].[T143MESSAGETEMPLATE] ([T143ID]) ON DELETE CASCADE


END
GO

-- Controlla versione 200 (MRTCore 7.5.8)
IF COL_LENGTH('dbo.T59COMSTORICOBV', 'T59DATACONGEDOVISITATORE') IS NOT NULL
BEGIN
	PRINT 'Script level 200 ok'
END
ELSE
BEGIN
	-- Script di update DB con campi per congedo visitatore, MrtCore 7.5.8

	ALTER TABLE [dbo].[T59COMSTORICOBV] ADD [T59DATACONGEDOVISITATORE] [datetime]
	ALTER TABLE [dbo].[T59COMSTORICOBV] ADD [T59OFFSETCONGEDOVISITATORE] [int] NOT NULL DEFAULT 0
	ALTER TABLE [dbo].[T59COMSTORICOBV] ADD [T59DATAUSCITAVISITATORE] [datetime]
END
GO

-- Controlla versione 300 (MRTCore 7.5.10)
IF OBJECT_ID(N'dbo.T07TIPOLOGIEDOCUMENTO', N'U') IS NOT NULL
BEGIN
	PRINT 'Script level 300 ok'
END
ELSE
BEGIN

    -- MrtCore 7.5.10
    -- Script update campo cod catastale su T83
    -- Nuova tabella tipologie documento T07
    -- Modifica lunghezza campi e T21USBREADER non nullabile

    UPDATE T21COMUTENTI SET T21USBREADER=0 WHERE T21USBREADER IS NULL
    DECLARE @var0 nvarchar(128)
    SELECT @var0 = name
    FROM sys.default_constraints
    WHERE parent_object_id = object_id(N'dbo.T21COMUTENTI')
    AND col_name(parent_object_id, parent_column_id) = 'T21USBREADER';
    IF @var0 IS NOT NULL
        EXECUTE('ALTER TABLE [dbo].[T21COMUTENTI] DROP CONSTRAINT [' + @var0 + ']')
    ALTER TABLE [dbo].[T21COMUTENTI] ALTER COLUMN [T21USBREADER] [int] NOT NULL
    ALTER TABLE [dbo].[T21COMUTENTI] ADD CONSTRAINT [DF_dbo.T21COMUTENTI_T21USBREADER] DEFAULT 0 FOR [T21USBREADER]
    DECLARE @var1 nvarchar(128)
    SELECT @var1 = name
    FROM sys.default_constraints
    WHERE parent_object_id = object_id(N'dbo.T129COMDMAIL')
    AND col_name(parent_object_id, parent_column_id) = 'T129ATTACHNAME';
    IF @var1 IS NOT NULL
        EXECUTE('ALTER TABLE [dbo].[T129COMDMAIL] DROP CONSTRAINT [' + @var1 + ']')
    ALTER TABLE [dbo].[T129COMDMAIL] ALTER COLUMN [T129ATTACHNAME] [nvarchar](255) NULL
    DECLARE @var2 nvarchar(128)
    SELECT @var2 = name
    FROM sys.default_constraints
    WHERE parent_object_id = object_id(N'dbo.T129COMDMAIL')
    AND col_name(parent_object_id, parent_column_id) = 'T129ATTACHTYPE';
    IF @var2 IS NOT NULL
        EXECUTE('ALTER TABLE [dbo].[T129COMDMAIL] DROP CONSTRAINT [' + @var2 + ']')
    ALTER TABLE [dbo].[T129COMDMAIL] ALTER COLUMN [T129ATTACHTYPE] [nvarchar](255) NULL
    CREATE TABLE [dbo].[T07TIPOLOGIEDOCUMENTO] (
        [T07ID] [int] NOT NULL IDENTITY,
        [T07CODICE] [nvarchar](50) NOT NULL,
        [T07DESCRIZIONE] [nvarchar](255),
        [T07SCADENZA] [int],
        [T07AVVISOSCADENZA] [int],
        [T07IMPOSTASCADENZA] [bit] NOT NULL,
        [T07MODSCADENZA] [bit] NOT NULL,
        [T07MAXDOCUMENTI] [int],
        [T07MULTILINGUA] [bit] NOT NULL,
        [T07MAXFILES] [int],
        [T07SORGENTI] [smallint] NOT NULL,
        [T07ESTENSIONI] [nvarchar](255),
        [T07DATAORAMODIFICA] [datetime] NOT NULL,
        [T07UTENTEMODIFICA] [nvarchar](64) NOT NULL,
        CONSTRAINT [PK_dbo.T07TIPOLOGIEDOCUMENTO] PRIMARY KEY ([T07ID])
    )
    CREATE UNIQUE INDEX [IX_Codice] ON [dbo].[T07TIPOLOGIEDOCUMENTO]([T07CODICE])
    ALTER TABLE [dbo].[T137COMDOCUMENTALE] ADD [T137TIPODOCUMENTO] [int]
    ALTER TABLE [dbo].[T83COMCOMUNIITALIANI] ADD [T83CODCATASTALE] [nvarchar](4) NOT NULL DEFAULT ''
    CREATE INDEX [IX_T137TIPODOCUMENTO] ON [dbo].[T137COMDOCUMENTALE]([T137TIPODOCUMENTO])
    ALTER TABLE [dbo].[T137COMDOCUMENTALE] ADD CONSTRAINT [FK_dbo.T137COMDOCUMENTALE_dbo.T07TIPOLOGIEDOCUMENTO_T137TIPODOCUMENTO] FOREIGN KEY ([T137TIPODOCUMENTO]) REFERENCES [dbo].[T07TIPOLOGIEDOCUMENTO] ([T07ID])

END
GO

-- Controlla versione 400 (MRTCore 7.5.13)
IF OBJECT_ID(N'dbo.T08NOTEANAGRAFICHE', N'U') IS NOT NULL
BEGIN
	PRINT 'Script level 400 ok'
END
ELSE
BEGIN

    -- MrtCore 7.5.13
    -- Nuova tabella note anagrafiche T08
    -- Nuove colonne in T07, T137 e T142

    CREATE TABLE [dbo].[T08NOTEANAGRAFICHE] (
        [T08ID] [int] NOT NULL IDENTITY,
        [T08CODICE] [nvarchar](8) NOT NULL,
        [T08TIPOCODICE] [nvarchar](1) NOT NULL,
        [T08CODAZIENDA] [nvarchar](8),
        [T08TIPO] [int] NOT NULL,
        [T08TESTO] [nvarchar](500) NOT NULL,
        [T08DATAORA] [datetime] NOT NULL,
        [T08UTENTE] [nvarchar](255),
        [T08CODTERMINALE] [nvarchar](8),
        [T08CODVARCO] [nvarchar](8),
        CONSTRAINT [PK_dbo.T08NOTEANAGRAFICHE] PRIMARY KEY ([T08ID])
    )
    CREATE INDEX [IX_T08DATAORA] ON [dbo].[T08NOTEANAGRAFICHE]([T08DATAORA])
    CREATE INDEX [IX_T08UTENTE] ON [dbo].[T08NOTEANAGRAFICHE]([T08UTENTE])
    CREATE INDEX [IX_T08CODVARCO] ON [dbo].[T08NOTEANAGRAFICHE]([T08CODVARCO])

    -- Modifica tipologie documento
    ALTER TABLE [dbo].[T07TIPOLOGIEDOCUMENTO] ADD [T07TIPOSCADENZA] [int] NOT NULL DEFAULT 0
    ALTER TABLE [dbo].[T07TIPOLOGIEDOCUMENTO] ADD [T07TIPIANAGRAFICHE] [int] NOT NULL DEFAULT 0
    GO

    -- Migrazione dati
    UPDATE T07TIPOLOGIEDOCUMENTO SET T07TIPOSCADENZA = 0 WHERE T07IMPOSTASCADENZA=0 AND T07SCADENZA IS NULL
    UPDATE T07TIPOLOGIEDOCUMENTO SET T07TIPOSCADENZA = 1 WHERE T07IMPOSTASCADENZA=1
    UPDATE T07TIPOLOGIEDOCUMENTO SET T07TIPOSCADENZA = 3 WHERE T07IMPOSTASCADENZA=0 AND T07SCADENZA IS NOT NULL
    UPDATE T07TIPOLOGIEDOCUMENTO SET T07TIPIANAGRAFICHE = 127
    -- Flag ricevuto
    UPDATE T137COMDOCUMENTALE SET T137RICEVUTO = '1' WHERE T137TIPODOCUMENTO IS NOT NULL OR T137TIPOCODICE='2' OR T137TIPOCODICE='L'
    -- Rettifica scadenza non impostata su documenti
    UPDATE T137COMDOCUMENTALE SET T137DATASCAD = '99991231' WHERE T137WARNING='0'
    GO

    -- Nuove colonne T137
    ALTER TABLE [dbo].[T137COMDOCUMENTALE] ADD [T137DATAINS] [datetime]
    GO
    UPDATE dbo.T137COMDOCUMENTALE SET T137DATAINS = GetDate()
    ALTER TABLE [dbo].[T137COMDOCUMENTALE] ALTER COLUMN [T137DATAINS] [datetime] NOT NULL

    ALTER TABLE [dbo].[T137COMDOCUMENTALE] ADD [T137DATAMODIFICA] [datetime]
    GO
    UPDATE dbo.T137COMDOCUMENTALE SET T137DATAMODIFICA = GetDate()
    ALTER TABLE [dbo].[T137COMDOCUMENTALE] ALTER COLUMN [T137DATAMODIFICA] [datetime] NOT NULL
    ALTER TABLE [dbo].[T137COMDOCUMENTALE] ADD [T137UTENTEMODIFICA] [nvarchar](64)

    -- Nuove colonne T142
    ALTER TABLE [dbo].[T142COMDETTDOCUMENTALE] ADD [T142DATAINS] [datetime]
    GO
    UPDATE dbo.T142COMDETTDOCUMENTALE SET T142DATAINS = GetDate()
    ALTER TABLE [dbo].[T142COMDETTDOCUMENTALE] ALTER COLUMN [T142DATAINS] [datetime] NOT NULL
    ALTER TABLE [dbo].[T142COMDETTDOCUMENTALE] ADD [T142DATAMODIFICA] [datetime]
    GO
    UPDATE dbo.T142COMDETTDOCUMENTALE SET T142DATAMODIFICA = GetDate()
    ALTER TABLE [dbo].[T142COMDETTDOCUMENTALE] ALTER COLUMN [T142DATAMODIFICA] [datetime] NOT NULL
    ALTER TABLE [dbo].[T142COMDETTDOCUMENTALE] ADD [T142UTENTEMODIFICA] [nvarchar](64)

    -- Drop colonna
    DECLARE @var0 nvarchar(128)
    SELECT @var0 = name
    FROM sys.default_constraints
    WHERE parent_object_id = object_id(N'dbo.T07TIPOLOGIEDOCUMENTO')
    AND col_name(parent_object_id, parent_column_id) = 'T07IMPOSTASCADENZA';
    IF @var0 IS NOT NULL
        EXECUTE('ALTER TABLE [dbo].[T07TIPOLOGIEDOCUMENTO] DROP CONSTRAINT [' + @var0 + ']')
    ALTER TABLE [dbo].[T07TIPOLOGIEDOCUMENTO] DROP COLUMN [T07IMPOSTASCADENZA]

END
GO

-- Controlla versione 500 (MRTCore 7.5.14)
IF COL_LENGTH('dbo.T37ACCTRANSITI', 'T37CODAZIENDADIPENDENTE') IS NOT NULL
BEGIN
	PRINT 'Script level 500 ok'
END
ELSE
BEGIN

    -- MrtCore 7.5.14
    -- Nuovi campi per storicizzazione dati dip. riferimento in T37

    ALTER TABLE [dbo].[T37ACCTRANSITI] ADD [T37CODAZIENDADIPENDENTE] [nvarchar](8)
    ALTER TABLE [dbo].[T37ACCTRANSITI] ADD [T37DESCRAZIENDADIPENDENTE] [nvarchar](60)
    ALTER TABLE [dbo].[T37ACCTRANSITI] ADD [T37MATRICOLADIPENDENTE] [nvarchar](8)
    ALTER TABLE [dbo].[T37ACCTRANSITI] ADD [T37COGNOMEDIPENDENTE] [nvarchar](40)
    ALTER TABLE [dbo].[T37ACCTRANSITI] ADD [T37NOMEDIPENDENTE] [nvarchar](40)
    ALTER TABLE [dbo].[T37ACCTRANSITI] ADD [T37CODMANSIONEDIPENDENTE] [nvarchar](4)
    ALTER TABLE [dbo].[T37ACCTRANSITI] ADD [T37DESCRMANSIONEDIPENDENTE] [nvarchar](60)
    ALTER TABLE [dbo].[T37ACCTRANSITI] ADD [T37CODREPARTODIPENDENTE] [nvarchar](8)
    ALTER TABLE [dbo].[T37ACCTRANSITI] ADD [T37DESCRREPARTODIPENDENTE] [nvarchar](60)

END
GO

-- Controlla versione 600 (MRTCore 7.5.15)
IF COL_LENGTH('dbo.T141ACCQYBUFFER', 'T141TIPORECORD') IS NOT NULL
BEGIN
	PRINT 'Script level 600 ok'
END
ELSE
BEGIN

    -- MrtCore 7.5.15
    -- Nuovo campo T141TIPORECORD

    ALTER TABLE [dbo].[T141ACCQYBUFFER] ADD [T141TIPORECORD] [nvarchar](1)
    GO
    UPDATE dbo.T141ACCQYBUFFER SET T141TIPORECORD='P'
    GO
    ALTER TABLE [dbo].[T141ACCQYBUFFER] ALTER COLUMN [T141TIPORECORD] [nvarchar](1) NOT NULL

END
GO

-- TODO AGGIUNGERE QUI LE PROSSIME VERSIONI


-- Blacklist history e T154
DECLARE @BLACK AS INT
DECLARE @T154 AS INT

SELECT @BLACK = OBJECT_ID(N'dbo.BLACKLISTHISTORYT', N'U')
SELECT @T154 = OBJECT_ID(N'dbo.T154ACCOVERRIDETECNID', N'U')

IF (@BLACK IS NULL) AND (@T154 IS NULL)
BEGIN
	RETURN;
END
    
-- Tabelle aggiuntive
PRINT ''
PRINT 'Tabelle aggiuntive'

IF (@BLACK IS NOT NULL) 
BEGIN
    PRINT 'Blacklist history'
END

IF (@T154 IS NOT NULL) 
BEGIN
    PRINT 'Tabella setup testine aggiuntive T154'
END



